### ISSUE TITLE
Error use_bundler_config? and File.exists? 'Gemfile'

### ISSUE THREAD

**Issue by IanVaughan** [git-up/GitUp#912]
```
> git up
Fetching origin
main                                   up to date
staging                                diverged
/Users/ianvaughan/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/git-up-0.5.12/lib/git-up.rb:285:in `use_bundler?': undefined method `exists?' for File:Class (NoMethodError)

    use_bundler_config? and File.exists? 'Gemfile'
                                ^^^^^^^^
Did you mean?  exist?
        from /Users/ianvaughan/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/git-up-0.5.12/lib/git-up.rb:233:in `check_bundler'
        from /Users/ianvaughan/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/git-up-0.5.12/lib/git-up.rb:27:in `run'
        from /Users/ianvaughan/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/git-up-0.5.12/bin/git-up:5:in `<top (required)>'
        from /Users/ianvaughan/.asdf/installs/ruby/3.2.0/bin/git-up:25:in `load'
        from /Users/ianvaughan/.asdf/installs/ruby/3.2.0/bin/git-up:25:in `<main>'

> ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]
 
> gem list  | grep git-up
git-up (0.5.12)
```

**Comment by lucasderraugh** [comment]
`git up` isn't a command from this app. `gitup` is.
